Extend debian/mkpackage to populate a PPA for Ubuntu users

diff --git a/debian/mkpackage b/debian/mkpackage
--- a/debian/mkpackage
+++ b/debian/mkpackage
@@ -8,9 +8,36 @@ VERSION='v0.97.1'
 
 export DEBEMAIL='dave@daveking.com'
 
-#  Run in interactive containers with a /bin/sh trap on failure 
-DEBUG=true
+usage () {
+	echo "Usage: $0 [-d] [-h] [-t]"
+	echo "    where:"
+	echo "        -d : keep container open for debugging when there is  an error"
+	echo "        -t : test build, do not publish the results to the PPA"
+}
 
+DEBUG=false
+TESTBUILD=false
+while getopts "dth" OPT; do
+	case "${OPT}" in
+		d)
+			DEBUG=true
+			;;
+		t)
+			TESTBUILD=true
+			;;
+		h)
+			usage
+			exit
+			;;
+		*)
+			echo "Invalid option: $OPT"
+			usage
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND-1))
+	
 #  Name of the Fedora container we use as the base for our container build
 UBUNTU_CONTAINER="ubuntu:latest"
 
@@ -21,16 +48,9 @@ if [ $(cat /etc/hostname) == "fang.localdomain" ]; then
 
 	#  This section of the script does not run in the podman container, it only
 	#  runs on the container's host and drives the overall build process
-
-	#  Set to "true" to test the package build process in an interactive 
-	#  VM.  The package will not be submitted to the PPA.
-	#
-	#  Need to have installed the QEMU emulation package: qemu-user-static
-	TESTBUILD=false
-
 	cd $(dirname $(realpath "$0"))
 
-	#  Build the debs
+	#  Build the debs in a container
 	echo "Starting build at $(date +%H:%m:%S)"
 	OPT=""
 	if $DEBUG; then
@@ -40,8 +60,60 @@ if [ $(cat /etc/hostname) == "fang.localdomain" ]; then
 	echo "Build complete at $(date +%H:%m:%S)"
 	echo "That took $(elapsed $STARTTIME)"
 		
-	if [ ! $TESTBUILD ]; then
-		echo 'submit debs to ppa here'
+	#  If this isn't a test, put the deb files into my PPA
+	if [ $TESTBUILD == false ]; then
+	
+		#  Update PPA
+		rm -fr /tmp/ppa &>/dev/null || true
+		rsync --archive --partial --progress daveking.com:/opt/autokey-wayland-ppa/ /tmp/ppa/
+		mv ${HOME}/Downloads/autokey*.deb /tmp/ppa/
+		cd /tmp/ppa
+		dpkg-scanpackages --multiversion . >Packages
+		gzip -k -f Packages
+	    
+		# Create the Releases file in the repo
+		echo "Creating Release files for PPA"
+		cd "/tmp/ppa"
+		# Create the Release file in the repo
+		echo "Creating Release file in ${PPADIR%%/}/dists/$SUBDIR"
+		
+		do_hash() {
+			HASH_NAME=$1
+			HASH_CMD=$2
+			echo "${HASH_NAME}:"
+			for f in $(find -type f); do
+				f=$(echo $f | cut -c3-) # remove ./ prefix
+				if [[ $f == Release* ]] || [[ $f == InRelease* ]] || [[ $f == index.html ]] || [[ $f == markdown.css ]] || [[ $f == pgp-key.public ]]; then
+					continue
+				fi
+				echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
+			done
+		}
+
+		cat << EOF > Release
+Origin: autokey-wayland Repository
+Label: autokey-wayland
+Suite: unstable
+Codename: unstable
+Version: 1.0
+Architectures: all
+Components: main
+Description: AutoKey for Wayland
+Date: $(date -Ru)
+EOF
+		do_hash "MD5Sum" "md5sum" >> Release
+		do_hash "SHA1" "sha1sum" >> Release
+		do_hash "SHA256" "sha256sum" >> Release
+
+		#  Sign the Release file
+		echo "Signing the Release file"
+		export GNUPGHOME=${HOME}/.gnupg-ppakey
+		cat Release | gpg -abs >Release.gpg
+		cat Release | gpg -abs --clearsign >InRelease
+
+		echo "Sync local repo with remote web site"
+		rsync --archive --partial --progress --delete /tmp/ppa/ daveking.com:/opt/autokey-wayland-ppa/
+		echo "Sync complete"
 	fi
 
 else
